[package]
name = "tmp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plastic-io = { git = "https://github.com/plastic-io/plastic-io-rust.git", version = "0.1.0" }
